# Generated by Django 5.2.5 on 2025-10-06 09:23

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=invoices.models.InvoiceFileS3Storage, upload_to=invoices.models.get_invoice_s3_file_path)),
            ],
        ),
    ]
