# Generated by Django 5.2.5 on 2025-10-08 08:20

import invoices.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(access_key='admin', bucket_name='sfspapi', endpoint_url='http://service-s3-bucket:9000', region_name='us-east-1', secret_key='administrator', use_ssl=False, verify=True), upload_to=invoices.models.get_invoice_s3_file_path)),
            ],
        ),
    ]
