---
services:
  # Dependency services 
  # add any dependency service like databases and others. For testing here.
  service-db:
    container_name: &database-container-name service-db
    image: postgres
    environment:
      POSTGRES_USER: &database-username postgres
      POSTGRES_PASSWORD: &database-password postgres
      POSTGRES_DB: &database-service-db-name api

  service-s3-bucket:
    container_name: &s3-bucket-db-container-name service-s3-bucket
    command: server --console-address ":9001" /data
    image: minio/minio
    ports:
      - "9001:9001"
      - "9000:9000"
    expose:
      - 9000
    environment:
      MINIO_ROOT_USER: &s3-bucket-db-root-user admin
      MINIO_ROOT_PASSWORD: &s3-bucket-db-root-password administrator

  # Update this to the name of the service you want to work with in your docker-compose.yml file
  api:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile

    # Set environment variables here directly
    environment:
      DB_NAME: *database-service-db-name
      DB_USER: *database-username
      DB_PASSWORD: *database-password
      DB_HOST: *database-container-name
      DB_PORT: 5432

      S3_BUCKET_NAME: sfspapi
      S3_USER: *s3-bucket-db-root-user
      S3_PASSWORD: *s3-bucket-db-root-password
      S3_HOST: *s3-bucket-db-container-name # must be added to pc's hosts file with "s3-bucket-db-container-name" pointing to 127.0.0.1
      S3_PORT: 9000

    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"